# wrangler.toml — Ergodika API (Cloudflare Worker)
name = "ergodika-api"
main = "src/index.js"
compatibility_date = "2024-09-10"

# Usiamo il dominio personalizzato (niente *.workers.dev)
workers_dev = false

# Route che collega il Worker all'host www.ergodika.it/api nella zona ergodika.it
routes = [
  { pattern = "www.ergodika.it*", zone_name = "ergodika.it" }
]

# Variabili NON sensibili (ok in repo)
[vars]
SITE_URL = "https://www.ergodika.it"
ALLOWED_ORIGINS = "https://www.ergodika.it,https://ergodika.it"
CONNECT_FEE_PERCENT = "20"
GOOGLE_REDIRECT_URL = "https://www.ergodika.it/api/auth/google/callback"
# Chiave pubblicabile Stripe (NON è segreta, ok nel repo)
STRIPE_PUBLISHABLE = "pk_live_51S5p3vRrORapViIm8xZ27PHOkSYwZpPPnFgfFW8G4rIzCJblqvkz2sSJJtyoqrPEhei7Pn50TIgoV9ngRFqlZ5KI00XXUtIMks"

# KV: trasparenza/contatori & mapping artisti→account Connect
[[kv_namespaces]]
binding = "ERGODIKA"
id = "5ea4fe53af054fe3933b52ca81b29566"

# D1: database utenti/sessioni
[[d1_databases]]
binding = "DB"
database_name = "ergodika"
database_id = "9a27eb90-4948-4b40-8fab-d5497ec4a61a"
