# wrangler.toml — Ergodika API (Cloudflare Worker)
name = "ergodika-api"
main = "src/index.js"
compatibility_date = "2024-09-10"

# Same-origin API under www.ergodika.it
workers_dev = true

# IMPORTANT: add both the exact path and the wildcard,
# because Cloudflare route '.../api/*' does NOT match '/api' without trailing slash.
routes = [
  { pattern = "www.ergodika.it/api", zone_name = "ergodika.it" },
  { pattern = "www.ergodika.it/api/*", zone_name = "ergodika.it" }
]

[vars]
SITE_URL = "https://www.ergodika.it"
ALLOWED_ORIGINS = "https://www.ergodika.it,https://ergodika.it"
CONNECT_FEE_PERCENT = "20"
GOOGLE_REDIRECT_URL = "https://www.ergodika.it/api/auth/google/callback"
# Public Stripe key (safe in repo)
STRIPE_PUBLISHABLE = "pk_live_51S5p3vRrORapViIm8xZ27PHOkSYwZpPPnFgfFW8G4rIzCJblqvkz2sSJJtyoqrPEhei7Pn50TIgoV9ngRFqlZ5KI00XXUtIMks"
COOKIE_DOMAIN = ".ergodika.it"

[[kv_namespaces]]
binding = "ERGODIKA"
id = "5ea4fe53af054fe3933b52ca81b29566"

[[d1_databases]]
binding = "DB"
database_name = "ergodika"
database_id = "9a27eb90-4948-4b40-8fab-d5497ec4a61a"
